spring:
  config:
    import: classpath:secret.yml
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.local_url}
    username: ${mysql.local_username}
    password: ${mysql.local_password}

logging:
  level:
    root: INFO
    com.pedia.movie: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE