mysql:
  local_url: jdbc:mysql://localhost:3306/movielocaldb
  local_username: root
  local_password: 1234
  deploy_url: jdbc:mysql://localhost:3306/moviedevdb
  deploy_username: devdbuser
  deploy_password: devdbpassword

kobis:
  api:
    url: "http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"
    week_url: "http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json"
    key: "a875bf3a1617df890463015899087614"


tmdb:
  api:
    url: https://api.themoviedb.org/3/search/movie
    key: "91aa608a9c61abc62790e12ea059c23f"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tjsdn0011@gmail.com
    password: ixdmmvbaznysecsm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true